[workspace]
members = [
    "datafusion-optd-cli",
    "optd-core",
    "optd-datafusion-bridge",
    "optd-datafusion-repr",
    "optd-sqlplannertest",
    "optd-adaptive-demo",
    "gungnir",
]
resolver = "2"
