name: lint and test

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo test
      